### ISSUE TITLE
BUG : Variable in destination path is not parsed

### ISSUE THREAD

**Issue by oslo10e** [carlo-colombo/grunt-angular-modules-graph#16]
when I use a variable to define destination of modules-graph files :
yeoman.doc = "documentation"

```
'modules-graph': {
 dev: {
  files: {
    '<%= yeoman.doc %>/dependencies-graph.dot': ['*.js']
  }
 }
},
```

it generates a <%= yeoman.doc %>/dependencies-graph.dot file instead of documentation/dependencies-graph.dot

**Comment by carlo-colombo** [comment]
I dismissed this project, you should check https://github.com/lucalanca/grunt-angular-architecture-graph that is an improved version of my task
