### ISSUE TITLE
publish module sans the grunt cruft

### ISSUE THREAD

**Issue by btford** [carlo-colombo/grunt-angular-modules-graph#3]
It would be nice to publish just `angular-modules-graph` with a function signature like:

``` javascript
var dotOutputAsAString = angularModulesGraph([ 'array of strings of angular app file contents' ]);
```

This module could then depend on the new one.

**Comment by carlo-colombo** [comment]
Good idea! Do you already have an idea about using this standalone module without grunt cruft?

**Comment by btford** [comment]
I have a couple vague ideas of what I'd like to use this for, but nothing too concrete.

**Comment by carlo-colombo** [comment]
I created [module angular-modules-graph](https://github.com/carlo-colombo/angular-modules-graph).
